# Generated by Django 5.1 on 2024-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(null=True, upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Cover'),
        ),
    ]
